# Generated by Django 4.2.14 on 2024-11-20 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code2', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='2字母代码')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='名称')),
                ('cn_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='中文名称')),
                ('flag', models.CharField(blank=True, max_length=150, null=True, verbose_name='国旗')),
                ('local_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='本地名称')),
                ('code3', models.CharField(blank=True, max_length=150, null=True, verbose_name='3字母代码')),
                ('lang_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='官方语言代码')),
                ('language', models.CharField(blank=True, max_length=150, null=True, verbose_name='官方语言')),
                ('continents', models.CharField(blank=True, max_length=150, null=True, verbose_name='归属洲')),
                ('phone_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='国际电话区号')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
                'ordering': ['code2'],
            },
        ),
        migrations.CreateModel(
            name='SerialNumberPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='序列号池名称')),
                ('description', models.CharField(blank=True, max_length=225, null=True, verbose_name='序列号池描述')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='序列号前缀')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='序列号后缀')),
                ('year', models.BooleanField(default=False, verbose_name='年')),
                ('month', models.BooleanField(default=False, verbose_name='月')),
                ('day', models.BooleanField(default=False, verbose_name='日')),
                ('digit', models.PositiveSmallIntegerField(default=5, verbose_name='位数')),
                ('step', models.PositiveIntegerField(default=1, verbose_name='序列号步长')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='下一个序列号的数字部分')),
            ],
            options={
                'verbose_name': '序列号池',
                'verbose_name_plural': '序列号池',
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='应用名称')),
                ('type', models.CharField(choices=[('WXH5', '微信H5'), ('WXXCX', '微信小程序'), ('WXAPP', '移动应用APP'), ('WXDYH', '微信订阅号'), ('WXFWH', '微信服务号'), ('ZFBXCX', '支付宝小程序'), ('DYXCX', '抖音小程序'), ('QQ', 'QQ'), ('YSFXCX', '云闪付小程序'), ('WXZF', '微信支付'), ('QYWX', '企业微信')], max_length=15, verbose_name='应用类型')),
                ('mchid', models.CharField(blank=True, max_length=150, null=True, verbose_name='商户id')),
                ('appid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Appid')),
                ('original_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='原始id')),
                ('secret', models.CharField(blank=True, max_length=150, null=True, verbose_name='Secret')),
                ('public_key', models.CharField(blank=True, max_length=150, null=True, verbose_name='公钥')),
                ('qrcode', models.ImageField(blank=True, max_length=225, null=True, upload_to='apps/', verbose_name='二维码')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='应用所属公司')),
                ('qywx_token', models.CharField(blank=True, max_length=150, null=True, verbose_name='企业微信应用token')),
                ('qywx_aeskey', models.CharField(blank=True, max_length=150, null=True, verbose_name='企业微信应用aeskey')),
                ('qywx_agent_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='企业微信应用id')),
                ('qywx_agent_secret', models.CharField(blank=True, max_length=150, null=True, verbose_name='企业微信应用密钥')),
                ('qywx_agent_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='企业微信应用名称')),
                ('notyfy_url', models.URLField(blank=True, null=True, verbose_name='回调地址')),
                ('welcome', models.CharField(blank=True, max_length=150, null=True, verbose_name='企业微信应用欢迎语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '禁用'), (1, '测试'), (2, '正式')], db_index=True, default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '第三方应用配置',
                'verbose_name_plural': '第三方应用配置',
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='SystemParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='参数名称')),
                ('key', models.CharField(db_index=True, max_length=50, verbose_name='键')),
                ('value', models.CharField(max_length=150, verbose_name='值')),
                ('value_type', models.CharField(choices=[('int', '整数'), ('float', '浮点型'), ('str', '字符串'), ('json', 'JSON')], default='str', max_length=15, verbose_name='值类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='编辑时间')),
                ('note', models.CharField(blank=True, max_length=225, null=True, verbose_name='备注')),
                ('status', models.BooleanField(db_index=True, default=True, verbose_name='状态')),
                ('lock_status', models.BooleanField(db_index=True, default=False, verbose_name='锁定状态')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'ordering': ['name', 'key'],
                'unique_together': {('name', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='编码')),
                ('province', models.CharField(db_index=True, max_length=50, verbose_name='省')),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='市')),
                ('district', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='区/县')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='system.country', verbose_name='国家')),
            ],
            options={
                'verbose_name': '省/市/区',
                'verbose_name_plural': '省/市/区',
                'ordering': ['code'],
                'unique_together': {('country', 'province', 'city', 'district')},
            },
        ),
    ]
