# Generated by Django 4.2.14 on 2024-11-20 22:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import libs.valid_error


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '手机号'), (2, '电子邮箱')], default=1, verbose_name='类型')),
                ('rec_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='接收号码')),
                ('code', models.PositiveIntegerField(verbose_name='验证码')),
                ('code_type', models.PositiveSmallIntegerField(choices=[(1, '注册/登录'), (2, '变更信息'), (3, '认证'), (4, '其他')], null=True, verbose_name='验证码类型')),
                ('uid', models.CharField(db_index=True, max_length=32, null=True, verbose_name='UID')),
                ('effective_time', models.PositiveIntegerField(default=0, verbose_name='有效期(s)')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '发送失败'), (2, '发送成功'), (3, '已使用'), (4, '已过期')], db_index=True, default=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '验证码记录',
                'verbose_name_plural': '验证码记录',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='UID')),
                ('role', models.CharField(choices=[('customer', '消费者'), ('agent', '商家')], max_length=25, null=True, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('username', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, validators=[libs.valid_error.valid_username], verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('sex', models.SmallIntegerField(choices=[(2, '女'), (1, '男'), (0, '待定')], default=0, verbose_name='性别')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
                ('head_img', models.CharField(max_length=150, null=True, verbose_name='头像')),
                ('phone_code', models.CharField(default='+86', max_length=15, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='电话')),
                ('idcard', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='身份证号码')),
                ('last_login_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='登录时间')),
                ('join_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='最后登录IP')),
                ('is_staff', models.BooleanField(default=False, verbose_name='内部员工')),
                ('status', models.SmallIntegerField(choices=[(-1, '删除'), (0, '禁用'), (1, '正常')], default=1, verbose_name='状态')),
                ('real_person_certification', models.BooleanField(default=0, verbose_name='是否实人认证')),
                ('pay_pwd', models.CharField(max_length=6, null=True, verbose_name='交易密码')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='system.country', verbose_name='国家')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=32, verbose_name='UID')),
                ('login_type', models.SmallIntegerField(choices=[(1, '密码'), (2, '手机短信'), (3, '微信'), (4, '支付宝')], default=1, verbose_name='登录类型')),
                ('client_type', models.CharField(choices=[('web', 'web端'), ('wx', '微信'), ('app', 'app'), ('zfb', '支付宝')], max_length=15, null=True, verbose_name='客户端类型')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('lon', models.FloatField(default=0.0, verbose_name='经度')),
                ('lat', models.FloatField(default=0.0, verbose_name='维度')),
                ('address', models.CharField(blank=True, max_length=225, null=True, verbose_name='地址')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('token', models.CharField(max_length=255, null=True, verbose_name='token串')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户登录日志',
                'verbose_name_plural': '用户登录日志',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserOpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=32, verbose_name='UID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('action_type', models.CharField(choices=[('read', '读'), ('add', '增'), ('update', '改'), ('delete', '删'), ('other', '其他')], max_length=32, verbose_name='操作类型')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('lon', models.FloatField(default=0.0, verbose_name='经度')),
                ('lat', models.FloatField(default=0.0, verbose_name='维度')),
                ('address', models.CharField(blank=True, max_length=225, null=True, verbose_name='地址')),
                ('tb_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='模型表名')),
                ('tb_desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='模型表描述')),
                ('tb_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='记录id')),
                ('tb_befor', models.CharField(blank=True, max_length=250, null=True, verbose_name='记录id')),
                ('tb_after', models.CharField(blank=True, max_length=250, null=True, verbose_name='记录id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserWX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=25, null=True, verbose_name='推荐人id')),
                ('head_img', models.CharField(max_length=150, null=True, verbose_name='微信头像')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信昵称')),
                ('open_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='openid')),
                ('union_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='unionid')),
                ('session_key', models.CharField(db_index=True, max_length=50, null=True, verbose_name='session_key')),
                ('access_token', models.CharField(max_length=150, null=True, verbose_name='access_token')),
                ('refresh_token', models.CharField(max_length=150, null=True, verbose_name='refresh_token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('third_apps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.thirdpartyapps', verbose_name='应用id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bind_wx', to='user.user', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户微信',
                'verbose_name_plural': '用户微信',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收件人姓名')),
                ('phone', models.CharField(max_length=15, verbose_name='收件人电话')),
                ('detail_address', models.CharField(max_length=225, verbose_name='详细地址')),
                ('zipcode', models.CharField(max_length=50, null=True, verbose_name='邮政编码')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='是否默认地址')),
                ('sort', models.PositiveIntegerField(db_index=True, default=5, verbose_name='排序')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '删除'), (1, '正常')], db_index=True, default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('address', models.ForeignKey(help_text='点击放大镜选择地址', on_delete=django.db.models.deletion.PROTECT, to='system.address', verbose_name='地址')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.country', verbose_name='国家')),
                ('uid', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='UID')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
            },
        ),
    ]
